FROM openjdk:8-jdk-alpine
RUN mkdir -p /usr/local/eurekaserver
WORKDIR /usr/local/eurekaserver
ADD ./target/eureka-service-0.0.1-SNAPSHOT.jar ./
CMD ["java", "-jar", "/usr/local/eurekaserver/eureka-service-0.0.1-SNAPSHOT.jar"]