version: '3'
services:
  eurekaserver:
    image: eurekaserver:0.1
    ports:
      - "28761:8761"
  configserver:
    image: configserver:0.1
    ports:
      - "28888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
  gatewayserver:
    image: gatewayserver:0.1
    ports:
      - "25000:5000"
    environment:
      SERVER_PORT: "5000"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
  exhibitserver:
    image: exhibitserver:0.1
    ports:
      - "28083:8083"
    environment:
      SERVER_PORT: "8083"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
  swaggerserver:
    image: swaggerserver:0.1
    ports:
      - "28085:8085"
    environment:
      SERVER_PORT: "8085"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"