server:
  port: 8083

spring:
  application:
    name: exhibitservice
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
  mvc:
    static-path-pattern: /static/**

eureka:
  instance:
    prefer-ip-address: true
    virtual-host-name: http://exhibitserver:8083
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/