-- WEEK_CHALLENGE_RECIPE  INSERT
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (150, NOW(), 'EASY', 'http://temp.com/temp/temp1.png', 1, '홍길동1', '도전레시피1');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (20, NOW(), 'MODERATE', 'http://temp.com/temp/temp2.png', 2, '홍길동2', '도전레시피2');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (25, NOW(), 'EASY', 'http://temp.com/temp/temp3.png', 3, '홍길동3', '도전레시피3');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (30, NOW(), 'HARD', 'http://temp.com/temp/temp4.png', 4, '홍길동4', '도전레시피4');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (50, NOW(), 'EASY', 'http://temp.com/temp/temp5.png', 5, '홍길동5', '도전레시피5');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (60, NOW(), 'MODERATE', 'http://temp.com/temp/temp6.png', 6, '홍길동6', '도전레시피6');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (75, NOW(), 'HARD', 'http://temp.com/temp/temp7.png', 7, '홍길동7', '도전레시피7');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (90, NOW(), 'EASY', 'http://temp.com/temp/temp8.png', 8, '홍길동8', '도전레시피8');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (10, NOW(), 'HARD', 'http://temp.com/temp/temp9.png', 9, '홍길동9', '도전레시피9');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (5, NOW(), 'MODERATE', 'http://temp.com/temp/temp0.png', 10, '홍길동10', '도전레시피10');
INSERT INTO WEEK_CHALLENGE_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (100, NOW(), 'HARD', 'http://temp.com/temp/temp1.png', 11, '홍길동11', '도전레시피11');

-- WEEK_BEST_RECIPE INSERT
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (150, NOW(), 'EASY', 'http://temp.com/temp/temp1.png', 1, '홍길동1', '도전레시피1');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (20, NOW(), 'MODERATE', 'http://temp.com/temp/temp2.png', 2, '홍길동2', '도전레시피2');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (25, NOW(), 'EASY', 'http://temp.com/temp/temp3.png', 3, '홍길동3', '도전레시피3');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (30, NOW(), 'HARD', 'http://temp.com/temp/temp4.png', 4, '홍길동4', '도전레시피4');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (50, NOW(), 'EASY', 'http://temp.com/temp/temp5.png', 5, '홍길동5', '도전레시피5');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (60, NOW(), 'MODERATE', 'http://temp.com/temp/temp6.png', 6, '홍길동6', '도전레시피6');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (75, NOW(), 'HARD', 'http://temp.com/temp/temp7.png', 7, '홍길동7', '도전레시피7');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (90, NOW(), 'EASY', 'http://temp.com/temp/temp8.png', 8, '홍길동8', '도전레시피8');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (10, NOW(), 'HARD', 'http://temp.com/temp/temp9.png', 9, '홍길동9', '도전레시피9');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (5, NOW(), 'MODERATE', 'http://temp.com/temp/temp0.png', 10, '홍길동10', '도전레시피10');
INSERT INTO WEEK_BEST_RECIPE (COOKING_TIME, CREATED, EASE, IMG_PATH, RECIPE_ID, REGISTER_NAME, TITLE) VALUES (100, NOW(), 'HARD', 'http://temp.com/temp/temp1.png', 11, '홍길동11', '도전레시피11');
