FROM openjdk:8-jdk-alpine
RUN mkdir -p /usr/local/configserver
WORKDIR /usr/local/configserver
ADD ./target/config-service-0.0.1-SNAPSHOT.jar ./
CMD ["java", "-jar", "/usr/local/configserver/config-service-0.0.1-SNAPSHOT.jar"]