server:
  port: 5000

spring:
  application:
    name: gatewayservice
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: exhibit_route
          uri: http://exhibitserver:8083
          predicates:
            - Path=/exhibitservice/**
        - id: swagger_route
          uri: http://swaggerserver:8085
          predicates:
            - Path=/swaggerservice/**
          filters:
            - RewritePath=/swaggerservice/(?<path>.*),/$\{path}
      discovery:
        locator:
          enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/