server:
  port: 5000

spring:
  application:
    name: gatewayservice
  profiles:
    active:
      default
  cloud:
    gateway:
      routes:
        - id: exhibit_route
          uri: http://exhibitserver:8083
          predicates:
            - Path=/exhibitservice/**
          filters:
            - name: AuthFilter
              args:
                preLogger: false
                postLogger: false
            - RewritePath=/exhibitservice/(?<path>.*),/$\{path}
        - id: swagger_route
          uri: http://swaggerserver:8085
          predicates:
            - Path=/swaggerservice/**
          filters:
            - RewritePath=/swaggerservice/(?<path>.*),/$\{path}
        - id: ingredient_route
          uri: http://ingredientserver:8086
          predicates:
            - Path=/ingredientservice/**
          filters:
            - name: AuthFilter
              args:
                preLogger: false
                postLogger: false
            - RewritePath=/ingredientservice/(?<path>.*),/$\{path}
        - id: oauth_route
          uri: http://oAuthServer:8080
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthFilter
              args:
                preLogger: false
                postLogger: false
            - RewritePath=/auth/(?<path>.*),/$\{path}
        - id: cooker_route
          uri: http://cooker:3000
          predicates:
            - Path=/cooker/**
          filters:
            - name: AuthFilter
              args:
                preLogger: false
                postLogger: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/