FROM openjdk:8-jdk-alpine
RUN mkdir -p /usr/local/swaggerserver
WORKDIR /usr/local/swaggerserver
ADD ./target/swagger-service-0.0.1-SNAPSHOT.jar ./
EXPOSE 5005
## ENTRYPOINT ["java", "-jar", "/usr/local/swaggerserver/target/*.jar"]