server:
  port: 8085

spring:
  application:
    name: swaggerservice
  profiles:
    active:
      default

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/