server:
  port: 8085

spring:
  application:
    name: swaggerservice
  profiles:
    active:
      default

eureka:
  instance:
    preferIpAddress: true
    non-secure-port: 28085
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/