-- INGREDIENT  INSERT
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (1, '육류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (2, '채소류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (3, '해산물');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (4, '유제품');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (5, '곡류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (6, '건어물');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (7, '과일류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (8, '버섯류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (9, '견과류');
INSERT INTO INGREDIENT_CATE (SEQ, `NAME`) VALUES (10, '기타');

-- INGREDIENT  INSERT
-- 육류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1001, 1, '소고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1002, 1, '돼지고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1003, 1, '닭고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1004, 1, '달걀');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1005, 1, '말고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1006, 1, '양고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1007, 1, '고래고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1008, 1, '오리고기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (1009, 1, '사슴고기');

-- 채소류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2001, 2, '가지');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2002, 2, '갓');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2003, 2, '감자');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2004, 2, '고구마');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2005, 2, '고사리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2006, 2, '고추');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2007, 2, '고추냉이');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2008, 2, '당근');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2009, 2, '더덕');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2010, 2, '도라지');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2011, 2, '돈나물');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2012, 2, '무');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2013, 2, '마');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2014, 2, '마늘');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2015, 2, '배추');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2016, 2, '브로콜리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2017, 2, '상추');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2018, 2, '생강');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2019, 2, '숙주나물');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2020, 2, '쑥');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2021, 2, '시금치');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2022, 2, '호박');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2023, 2, '양파');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2024, 2, '연근');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2025, 2, '오이');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2026, 2, '우엉');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2027, 2, '인삼');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2028, 2, '죽순');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2029, 2, '청경채');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2030, 2, '칡');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2031, 2, '콩나물');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2032, 2, '토마토');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2033, 2, '방울토마토');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (2034, 2, '파');

-- 해산물
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3001, 3, '오징어');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3002, 3, '갑오징어');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3003, 3, '꼴뚜기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3004, 3, '문어');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3005, 3, '낙지');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3006, 3, '주꾸미');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3007, 3, '전복');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3008, 3, '굴');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3009, 3, '소라');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3010, 3, '조개');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3011, 3, '가리비');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3012, 3, '꼬막');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3013, 3, '재첩');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3014, 3, '키조개');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3015, 3, '홍합');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3016, 3, '바지락');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3017, 3, '게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3018, 3, '꽃게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3019, 3, '홍게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3020, 3, '대게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3021, 3, '거미게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3022, 3, '민꽃게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3023, 3, '새우');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3024, 3, '흰다리새우');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3025, 3, '새우');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3026, 3, '얼룩새우');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3027, 3, '가재');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3028, 3, '바닷가재');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3029, 3, '딱새우');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3030, 3, '해삼');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3031, 3, '멍게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3032, 3, '성게');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3033, 3, '미더덕');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3034, 3, '해파리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3035, 3, '말미잘');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3036, 3, '캐비어');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3037, 3, '연어알');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3038, 3, '명란');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3039, 3, '이리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3040, 3, '곤이');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (3041, 3, '관자');

-- 유제품
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4001, 4, '우유');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4002, 4, '크림');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4003, 4, '크렘 프레쉬');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4004, 4, '클로티드 크림');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4005, 4, '우락유');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4006, 4, '분유');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4007, 4, '연유');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4008, 4, '리코타 치즈');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4009, 4, '치즈');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4010, 4, '구운 우유');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4011, 4, '버터');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4012, 4, '기버터');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4013, 4, '커드');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4014, 4, '코티지 치즈');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4015, 4, '크림 치즈');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4016, 4, '카세인');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4017, 4, '요거트');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4018, 4, '젤라토');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4019, 4, '아이스크림');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (4020, 4, '아이스밀크');

-- 곡류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5001, 5, '쌀');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5002, 5, '밀가루');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5003, 5, '옥수수');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5004, 5, '보리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5005, 5, '수수');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5006, 5, '귀리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5007, 5, '호밀');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5008, 5, '라이밀');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5009, 5, '메밀');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5010, 5, '포니오');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5011, 5, '퀴니아');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (5012, 5, '벼');

-- 건어물
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (6001, 6, '미역');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (6002, 6, '김');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (6003, 6, '멸치');

-- 버섯류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7001, 7, '노루궁뎅이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7002, 7, '송이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7003, 7, '팽이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7004, 7, '독버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7005, 7, '능이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7006, 7, '느타리버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7007, 7, '목이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7008, 7, '새송이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7009, 7, '송로버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7010, 7, '양송이버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7011, 7, '영지버섯');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (7012, 7, '표고버섯');

-- 과일류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8001, 8, '사과');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8002, 8, '레몬');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8003, 8, '수박');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8004, 8, '참외');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8005, 8, '멜론');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8006, 8, '귤');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8007, 8, '오렌지');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8008, 8, '포도');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8009, 8, '바나나');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8010, 8, '딸기');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8011, 8, '구기자');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8012, 8, '매실');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8013, 8, '무화과');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8014, 8, '복분자');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8015, 8, '복숭아');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8016, 8, '천도복숭아');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8017, 8, '자두');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8018, 8, '살구');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8019, 8, '감');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8020, 8, '대추');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8021, 8, '모과');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8022, 8, '배');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8023, 8, '석류');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8024, 8, '유자');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8025, 8, '한라봉');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8026, 8, '천혜향');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (8027, 8, '파인애플');

-- 견과류
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9001, 9, '콩');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9002, 9, '호두');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9003, 9, '땅콩');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9004, 9, '아몬드');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9005, 9, '밤');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9006, 9, '은행');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9007, 9, '헤이즐넛');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9008, 9, '피스타치오');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9009, 9, '캐슈넛');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9010, 9, '도토리');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9011, 9, '마카다미아');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9012, 9, '브라질너트');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9013, 9, '피칸');
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (9014, 9, '잣');

-- 기타
INSERT INTO INGREDIENT (SEQ, CATE_SEQ, `NAME`) VALUES (10011, 10, '기타');

-- UNIT  INSERT
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (10, 'each', 'ea');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (20, 'gram', 'gr');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (30, 'liter', 'lt');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (40, 'kilogram', 'kg');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (50, 'milliliter', 'ml');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (60, 'piece', 'pc');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (70, 'pinch', 'ph');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (80, 'slice', 'sl');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (90, 'clove', 'cl');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (100, 'pound', 'lb');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (110, 'ounce', 'oz');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (120, 'cup', 'C');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (130, 'tablespoon', 'T');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (140, 'teaspoon', 't');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (150, 'bundle', 'bn');
INSERT INTO UNIT(SEQ, CODE, `NAME`) VALUES (160, 'sheet', 'S/H');