server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-read-timeout-seconds: 15
    service-url:
      defaultZone: http://localhost:8761/eureka/