server:
  port: 8888

spring:
  application:
    name: configservice
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/